---
# tasks file for Instala-Tools
- name: "Instalar paquetes basicos" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux
    - tree
    - speedtest-cli
    - htop
